/node_modules/

## CI
/dist/
/log/
/build/
/lint/

.nyc_output/
coverage/

*.tgz

/ci/
Makefile

/examples/

/resources/*.schema.json

## IDE
*.code-workspace
.vscode/
.idea/

.git/

## OS
.DS_Store

.ns_template/

.nx/cache/
.nx/workspace-data/
